### ISSUE TITLE
missing documentation or example for rules_custom parameter

### ISSUE THREAD

**Issue by kayahk** [basisai/terraform-helm-prometheus-adapter#3]
I would appreciate if there was any hint regarding how to provide the `rules_custom`parameter. In my own helm_release resource, I used to provide the chart values including my custom rule like this (just an example and probably broken):

```
values = [<<EOF
prometheus:
  url: "http://prometheus-server.monitoring.svc"
  port: "80"

rules:
  custom:
  - seriesQuery: 'sum by (queue) (rabbitmq_queue_consumers)'
    resources:
      overrides:
        queue:
          resource: deployment
    name:
      matches: ^(.*)
      as: "${1}-hpa"
    metricsQuery: sum by (queue) (rabbitmq_queue_messages_unacked) / sum by (queue) (rabbitmq_queue_consumers)
EOF
  ]
  ```

The inputs table is just showing the `rules_custom` parameter as `type = list`, but I don't see how exactly to provide the object properly.
Given the circumstance, that a custom rule is likely to be the most common use case, it would help a lot to see how this is expected to be applied.

Thank you.
